/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cursojava.bhaskara;

import java.util.HashSet;

/**
 *
 * @author Pedro
 */
public class TelaEquacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaEquacao
     */
    public TelaEquacao() {
        initComponents();
        painel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpinnerB = new javax.swing.JSpinner();
        SpinnerC = new javax.swing.JSpinner();
        SpinnerA = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblEquacao = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblEquacao3 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblEquacao5 = new javax.swing.JLabel();
        lblEquacao6 = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        txtDeltaResult = new javax.swing.JLabel();
        txtX2Result = new javax.swing.JLabel();
        txtX1Result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SpinnerB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SpinnerB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerBStateChanged(evt);
            }
        });

        SpinnerC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SpinnerC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerCStateChanged(evt);
            }
        });

        SpinnerA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SpinnerA.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SpinnerAAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        SpinnerA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerAStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("X² +");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("X + ");

        btnCalcular.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblEquacao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEquacao.setText("Δ =");

        lblB.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblB.setForeground(new java.awt.Color(255, 0, 51));
        lblB.setText("B");

        lblEquacao3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEquacao3.setText("²   -4 ");

        lblC.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblC.setForeground(new java.awt.Color(255, 0, 51));
        lblC.setText("C");

        lblA.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblA.setForeground(new java.awt.Color(255, 0, 51));
        lblA.setText("A");

        lblEquacao5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEquacao5.setText("×");

        lblEquacao6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEquacao6.setText("×");

        txtDeltaResult.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDeltaResult.setText("Δ = ?");

        txtX2Result.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtX2Result.setText("X = ?");

        txtX1Result.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtX1Result.setText("X = ?");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtX1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX2Result, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeltaResult, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtDeltaResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtX1Result)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtX2Result)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEquacao)
                                .addGap(18, 18, 18)
                                .addComponent(lblB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEquacao3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEquacao5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEquacao6)
                                .addGap(15, 15, 15)
                                .addComponent(lblC))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnCalcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(SpinnerA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(SpinnerB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquacao)
                    .addComponent(lblB)
                    .addComponent(lblC)
                    .addComponent(lblA)
                    .addComponent(lblEquacao5)
                    .addComponent(lblEquacao6)
                    .addComponent(lblEquacao3))
                .addGap(27, 27, 27)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(SpinnerA.getValue().toString());
        int b = Integer.parseInt(SpinnerB.getValue().toString());
        int c = Integer.parseInt(SpinnerC.getValue().toString());
        double delta = (Math.pow(b,2) -4*a*c);
        painel.setVisible(true);
        txtDeltaResult.setText("Δ = " + delta);
        if (delta < 0){
            txtDeltaResult.setText("Não há raízes");
            txtX1Result.setVisible(false);
            txtX2Result.setVisible(false);
        } else if (delta == 0){
            double x = (-b + Math.sqrt(delta))/(2*a);
             txtX1Result.setText("X = " + x);
             txtX2Result.setVisible(false);
        } else if (delta > 0){
            double xI = (-b +Math.sqrt(delta))/(2*a);
            double xII = (-b -Math.sqrt(delta))/(2*a);
            txtX1Result.setText("X1 = " + xI);
            txtX2Result.setText("X2 = " + xII);
             txtX2Result.setVisible(true);
        } 
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void SpinnerAAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SpinnerAAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SpinnerAAncestorAdded

    private void SpinnerAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerAStateChanged
        // TODO add your handling code here:
        int a = Integer.parseInt(SpinnerA.getValue().toString());
        lblA.setText(Integer.toString(a));
    }//GEN-LAST:event_SpinnerAStateChanged

    private void SpinnerBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerBStateChanged
        // TODO add your handling code here:
        int b = Integer.parseInt(SpinnerB.getValue().toString());
        lblB.setText(Integer.toString(b));
    }//GEN-LAST:event_SpinnerBStateChanged

    private void SpinnerCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerCStateChanged
        // TODO add your handling code here:
        int c = Integer.parseInt(SpinnerC.getValue().toString());
        lblC.setText(Integer.toString(c));
    }//GEN-LAST:event_SpinnerCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEquacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEquacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerA;
    private javax.swing.JSpinner SpinnerB;
    private javax.swing.JSpinner SpinnerC;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblEquacao;
    private javax.swing.JLabel lblEquacao3;
    private javax.swing.JLabel lblEquacao5;
    private javax.swing.JLabel lblEquacao6;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel txtDeltaResult;
    private javax.swing.JLabel txtX1Result;
    private javax.swing.JLabel txtX2Result;
    // End of variables declaration//GEN-END:variables
}
